sudo: required
services: docker
language: minimal
env:
  - KUBERNETES_VERSION="v1.15.12" DOCKER_IMAGE_TAG="latest-1.15" MINIKUBE_VERSION="v1.0.1"
  - KUBERNETES_VERSION="v1.16.13" DOCKER_IMAGE_TAG="latest-1.16" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.17.9" DOCKER_IMAGE_TAG="latest-1.17" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.18.5" DOCKER_IMAGE_TAG="latest-1.18" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.19.3" DOCKER_IMAGE_TAG="latest-1.19" MINIKUBE_VERSION="v1.14.2"
script:
  - ./build.sh bsycorp/kind:$DOCKER_IMAGE_TAG bsycorp/kind:$KUBERNETES_VERSION
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    repo: bsycorp/kind
